Algoritmo "estrutura_escolha"
     //testes dias
Var

x  :inteiro
dia :caractere

Inicio
      leia (x)
     escolha x
     caso 1
     dia <- "domingo"
     caso 2
     dia <- "segunda"
     caso 3
     dia <- "terça
     caso 4
     dia <- "quarta"
     caso 5
     dia <- "quinta"
     caso 6
     dia <- "sexta"
     caso 7
     dia <- "sabado"
     outrocaso
     dia <- "opção invalida"
     
     fimescolha
     
     escreval("o dia da semana foi ", dia)

Fimalgoritmo