Algoritmo "TERRENO"

Var

   largura , comprimento , metroQuadrado, area, preco: real


Inicio
      escreval("Digite a largura do terreno:")
      leia(largura)
      escreval("Digite o comprimento do terreno:")
      leia(comprimento)
      escreval("Digite o valor do metro quadrado:")
      leia(metroQuadrado)
      
      area <- largura * comprimento)
      preco <- area * metroQuadrado
      escreval("a area é ", area:6:2)
      escreval("o preço é R$",preco:8:2)
      
Fimalgoritmo


